package photopanel.views;

import java.awt.Dimension;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import photopanel.boxes.datatypes.Datatype;

/**
 * EDITORPANEL - Tool- und Pluginprogrammierung 2016 - Hochschule Trier
 * @author Christian Colbach
 */
public class ShowResultFrame extends javax.swing.JFrame {

    private final SimpleDateFormat DATE_FORMAT = new SimpleDateFormat("dd-MM-yyyy HH:mm:SS");
        
    private Datatype data;
    /**
     * Creates new form ShowBitmapFrame
     */
    public ShowResultFrame(Datatype data) {
        this.data = data;
        initComponents();
        
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        Dimension dimension = ((ResultPanel)resultPanel).getIdealSize();
        resultPanel.setPreferredSize(dimension);
        setSize((int)dimension.getWidth()+20, (int)dimension.getHeight()+50);
        
        Date today = new Date();
        String date = DATE_FORMAT.format(today);
        
        setTitle(date + " " + data.getDescription());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        resultPanel = new ResultPanel(data);
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        resultPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                resultPanelMouseMoved(evt);
            }
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                resultPanelMouseDragged(evt);
            }
        });
        resultPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                resultPanelMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resultPanelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout resultPanelLayout = new javax.swing.GroupLayout(resultPanel);
        resultPanel.setLayout(resultPanelLayout);
        resultPanelLayout.setHorizontalGroup(
            resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 864, Short.MAX_VALUE)
        );
        resultPanelLayout.setVerticalGroup(
            resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 576, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(resultPanel);

        jMenu1.setText("File");

        jMenuItem1.setText("Speichern unter");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 654, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        
        JFileChooser chooser = new JFileChooser(".");
        int rueckgabeWert = chooser.showSaveDialog(this);
        if(rueckgabeWert == JFileChooser.APPROVE_OPTION) {
            File file = chooser.getSelectedFile();
            try {
                data.saveToFile(file);
            } catch (Exception exception) {
                exception.printStackTrace();

                JOptionPane.showMessageDialog(
                    null,
                    "Fehler: " + exception.getMessage(),
                    "Fehler",
                    JOptionPane.ERROR_MESSAGE
                );
            }
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void resultPanelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resultPanelMouseMoved
        ((ResultPanel) resultPanel).mousePositionChanged(evt.getX(), evt.getY());
        resultPanel.repaint();
    }//GEN-LAST:event_resultPanelMouseMoved

    private void resultPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resultPanelMousePressed
        ((ResultPanel) resultPanel).mousePressed(evt.getX(), evt.getY());
        resultPanel.repaint();
    }//GEN-LAST:event_resultPanelMousePressed

    private void resultPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resultPanelMouseClicked
        
    }//GEN-LAST:event_resultPanelMouseClicked

    private void resultPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resultPanelMouseDragged
        ((ResultPanel) resultPanel).mousePositionChanged(evt.getX(), evt.getY());
        resultPanel.repaint();
    }//GEN-LAST:event_resultPanelMouseDragged

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            // Set System L&F
//            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
//        } catch (UnsupportedLookAndFeelException e) {
//            // handle exception
//        } catch (ClassNotFoundException e) {
//            // handle exception
//        } catch (InstantiationException e) {
//            // handle exception
//        } catch (IllegalAccessException e) {
//            // handle exception
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ShowResultFrame(new SingleValue(12.333333, "Hallo")).setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel resultPanel;
    // End of variables declaration//GEN-END:variables
}
